In [1]:
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 3.3382e-31,  1.4013e-45, -5.2941e-04],
        [ 4.5891e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, -8.9854e+16]])


In [3]:
x = torch.rand(5, 3)

In [4]:
x

tensor([[0.0900, 0.1710, 0.3290],
        [0.5398, 0.9113, 0.5311],
        [0.0096, 0.0173, 0.4389],
        [0.0585, 0.1207, 0.6778],
        [0.0991, 0.6187, 0.4801]])

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)

In [6]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [7]:
x = torch.tensor([5.5, 3])

In [8]:
x

tensor([5.5000, 3.0000])

In [10]:
x = x.new_ones(5, 3, dtype=torch.double)

In [11]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [13]:
x = torch.randn_like(x, dtype=torch.float)

In [14]:
x

tensor([[ 0.1866,  1.2736, -0.2274],
        [ 1.9038,  0.0101, -0.5997],
        [-1.5373, -0.2512,  0.5943],
        [ 0.9305, -0.2992,  1.9545],
        [-0.5739,  0.0346,  0.0031]])

In [15]:
x.size()

torch.Size([5, 3])

In [16]:
y = torch.rand(5, 3)

In [17]:
y

tensor([[0.9656, 0.5238, 0.5898],
        [0.2022, 0.3259, 0.0631],
        [0.0537, 0.9084, 0.0623],
        [0.1277, 0.6508, 0.2102],
        [0.6579, 0.4099, 0.8763]])

In [18]:
x + y

tensor([[ 1.1523,  1.7973,  0.3625],
        [ 2.1060,  0.3359, -0.5366],
        [-1.4837,  0.6571,  0.6566],
        [ 1.0582,  0.3516,  2.1647],
        [ 0.0840,  0.4446,  0.8794]])

In [19]:
torch.add(x , y)

tensor([[ 1.1523,  1.7973,  0.3625],
        [ 2.1060,  0.3359, -0.5366],
        [-1.4837,  0.6571,  0.6566],
        [ 1.0582,  0.3516,  2.1647],
        [ 0.0840,  0.4446,  0.8794]])

In [20]:
result = torch.empty(5, 3)

In [21]:
result

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
torch.add(x, y, out=result)

tensor([[ 1.1523,  1.7973,  0.3625],
        [ 2.1060,  0.3359, -0.5366],
        [-1.4837,  0.6571,  0.6566],
        [ 1.0582,  0.3516,  2.1647],
        [ 0.0840,  0.4446,  0.8794]])

In [23]:
y.add_(x)

tensor([[ 1.1523,  1.7973,  0.3625],
        [ 2.1060,  0.3359, -0.5366],
        [-1.4837,  0.6571,  0.6566],
        [ 1.0582,  0.3516,  2.1647],
        [ 0.0840,  0.4446,  0.8794]])

In [24]:
x[:, 1]

tensor([ 1.2736,  0.0101, -0.2512, -0.2992,  0.0346])

In [25]:
x

tensor([[ 0.1866,  1.2736, -0.2274],
        [ 1.9038,  0.0101, -0.5997],
        [-1.5373, -0.2512,  0.5943],
        [ 0.9305, -0.2992,  1.9545],
        [-0.5739,  0.0346,  0.0031]])

In [26]:
a = torch.ones(5)

In [27]:
a

tensor([1., 1., 1., 1., 1.])

In [28]:
b = a.numpy()

In [29]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [30]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [31]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [35]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

In [36]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)